[package]
name = "poet_content"
description = "Builds Poet content documents, authors, collections and sitemaps"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
esbuild-metafile = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
markdown = { workspace = true }
nom = { workspace = true }
petgraph = { workspace = true }
poet_assets = { workspace = true }
poet_filesystem = { workspace = true }
poet_mdx = { workspace = true }
rayon = { workspace = true }
rhai = { workspace = true }
rhai_components = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sitemap-rs = { workspace = true }
slug = { workspace = true }
syntect = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
