[package]
description = "JSX-like syntax extension for Rhai"
edition.workspace = true
license.workspace = true
name = "rhai_components"
repository.workspace = true
version = "0.6.0"

[dependencies]
dashmap = { workspace = true }
rhai = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
