[package]
name = "poet_prompt"
description = "Turns Poet prompt documents into MCP prompts"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dashmap = { workspace = true }
esbuild-metafile = { workspace = true }
log = { workspace = true }
markdown = { workspace = true }
poet_assets = { workspace = true }
poet_content = { workspace = true }
poet_filesystem = { workspace = true }
poet_mcp = { workspace = true }
poet_mdx = { workspace = true }
rayon = { workspace = true }
rhai = { workspace = true }
rhai_components = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
