[package]
name = "poet_error_chain_tests"
autotests = false
description = "Integration tests for poet_error_chain"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
version.workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"

[dependencies]
poet_error_chain = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
