[package]
name = "poet_mdx"
description = "Parses MDX documents and renders their elements with Rhai shortcodes"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log = { workspace = true }
markdown = { workspace = true }
poet_filesystem = { workspace = true }
rhai = { workspace = true }
rhai_components = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
