[package]
name = "poet_prompt_tests"
autotests = false
description = "Integration tests for poet_prompt"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
version.workspace = true

[[test]]
name = "integration"
path = "tests/main.rs"

[dependencies]
esbuild-metafile = { workspace = true }
poet_assets = { workspace = true }
poet_content = { workspace = true }
poet_content_tests = { workspace = true }
poet_filesystem = { workspace = true }
poet_mcp = { workspace = true }
poet_mdx = { workspace = true }
poet_prompt = { workspace = true }
rhai = { workspace = true }
rhai_components = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
