name: cargo install

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup rust
        uses: ./.github/actions/setup-rust

      - name: install poet
        run: make install
        env:
          CARGO_INSTALL_ROOT: ${{ runner.temp }}/poet-install

      - name: run installed poet
        run: ${{ runner.temp }}/poet-install/bin/poet --version
