name: latest dependencies

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  latest-deps:
    name: latest-deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust
        uses: ./.github/actions/setup-rust

      - name: update dependencies to the latest compatible versions
        run: cargo update

      - name: run tests
        run: make test
