name: release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
      - v[0-9].[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:

jobs:
  resolve-version:
    name: resolve-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release-version.outputs.version }}
      name: ${{ steps.release-version.outputs.name }}
      description: ${{ steps.release-version.outputs.description }}
      type: ${{ steps.release-version.outputs.type }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - id: release-version
        uses: intentee/release-action/release-tag-to-version@8125f727e97f72bfef24299d7c6d3217af1453bc
        with:
          release-tag: "${{ github.ref_name }}"

  build:
    name: build
    needs: resolve-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: poet-bin-linux-amd64

          - os: macos-latest
            artifact_name: poet-bin-macos-arm

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build the binary
        run: make target/release/poet
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: rename the binary
        run: mv ./target/release/poet ./${{ matrix.artifact_name }}
        shell: bash

      - name: assert version matches tag
        uses: intentee/release-action/assert-version@8125f727e97f72bfef24299d7c6d3217af1453bc
        with:
          filename: "./${{ matrix.artifact_name }}"
          expected-version: "${{ needs.resolve-version.outputs.version }}"

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./${{ matrix.artifact_name }}

  release:
    name: release
    needs: [resolve-version, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: create release with all artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          name: ${{ needs.resolve-version.outputs.name }}
          body: ${{ needs.resolve-version.outputs.description }}
          prerelease: ${{ needs.resolve-version.outputs.type == 'PRE_RELEASE' }}
          tag_name: ${{ github.ref }}
